---
title: "Flatten The Curve: A Basic Epi. Model"
author: "Chris Berg"
date: "3/29/2020"
output: 
  html_document:
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Epidemiologists use mathematical models to understand how diseases spread throughout a population. [Dr. James Stock](https://drive.google.com/file/d/1Vu0wl-9K2dh8MpMqaO85MvE6UH7gcRLx/view) offers a simplified model based on more complicated epi. models, which I have been inspired [to simulate](https://rcberg.shinyapps.io/econepimodel/). This is just meant as a brief accompanying reader, on how [these basic epidemiological models](https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology#The_SIR_mode) work.

## Background

Epidemiologists model disease spread by looking at susceptible individuals, the infection rate, and the recovery rate. Populations start out with individuals susceptible to disease, and given an initial infected individual (*vector*) the disease spreads. As the population contracts the disease, they are classified as no-longer-susceptible because they will suffer from the disease, and then *recover* to a point of immunity where they aren't susceptible to the illness anymore.

### Quick note on deaths

This is a very simple model that just attempts to describe spread dynamics. There is no death-- individuals get the disease and eventually recover. Epidemiologists call these "non-vital" models. They have done a better job than me of adding things like mortality,  I might try and add that in the future at some point after reading the research.

## Simulation equations

The disease is described by a system of three equations at some given point in time $t$; one describing how the *susceptible* population changes, another describing how the *recovered* population changes, and lastly (but not least!) how the *infected* population changes.

\begin{align*}

\Delta S_t &= -\beta I_{t-1}\frac{S_{t-1}}{N} \\
\Delta R_t &= \gamma I_{t-1} \\
\Delta I_t &= \beta I_{t-1}\frac{S_{t-1}}{N} - \gamma I_{t-1}

\end{align*}

## Flattening the Curve 

Here $\beta$ is the *population transmission rate*, reflecting the rate which each infected person contaminates others each period. This transmission rate is what such "flatten-the-curve" policies like shelter-in-place orders and social distancing can reduce. Reducing it is the main way that we respond to disease outbreaks, in fact.  When using the app, notice that a smaller $\beta$ will flatten the infected persons curve. On the other hand $\gamma$ describes the rate at which infected persons recover. Sometimes they are expressed together as $R_0 = \frac{\beta}{\gamma}$.

Anyone reading this can [go to the app](https://rcberg.shinyapps.io/econepimodel/) and check out how much you'd need to lower the transmission rate to "flatten the curve" enough.

### Further explanation

The disease spreads at first because there are many susceptible individuals and few infected individuals. As it spreads, the population which is susceptible goes down (because they are either sick or recovered and thus immune), and infections eventually slow. The system settles to an equilibrium where the disease runs its course.